cmc and graviex price scripts
r001/setzer pull request #1
Opened 2019-07-26 08:53 UTC by vgaicuks

2019-07-26 12:28 UTC, r001 requested changes
Great job! I have a few minor comments.

2019-07-26 12:28 UTC, r001 commented on libexec/setzer/setzer-price-dpt-graviex
> +print((price_eth_usd / (1 / price_dpt_eth)).quantize(FOUR_PLACES))
When calculating prices from DPT/ETH and ETH/USD prices you do a double division instead of one multiplication. Please correct it.

2019-07-26 12:28 UTC, r001 commented on libexec/setzer/setzer-price-dpt-graviex
> +price_eth_usd = Decimal(json.loads(request.urlopen(COINMARKET_URL).read().decode())[0]['price_usd'])
In the script that gets graviex price you use the eth price form CMC. But if CMC is down you do not get a valid price even if graviex is up. So instead of getting the price from CMC get it via 'setzer price eth' because it will get it from different sources, and if at least one of them is running you have a valid ETH price.

2019-07-26 12:28 UTC, r001 commented on libexec/setzer/setzer-price-dpt-graviex
> +#!/usr/bin/env python3.6
Please add python3.6 to dependencies in file default.nix first line.

Would be nice to have this written in bash....

2019-07-29 08:05 UTC, vgaicuks commented
Changes has been made. Please check

2019-07-29 08:45 UTC, merged